### ISSUE TITLE
Assignment B-1 Feedback

### ISSUE THREAD

**Issue by albinagib** [stat545ubc-2021/lmPlot#1]
Hi Eve,

Great work on your Assignment B-1! Please see a few comments below that will help you improve your function for the next submission: 
- Tidy submission:  Excellent and highly detailed README.md file, reproducible code, good use of a release. You should be suppressing the messages when loading libraries by adding `suppressPackageStartupMessages()` around your library commands.
- Ex 1: Clear and well-written function.
- Ex 2: Great documentation.
- Ex 3: Great use of examples to illustrate your function.
- Ex 4: Good demonstration of `test_that()` function. You also used only one distinct expect function here (`expect_error()`) while you were asked to use at least three. 

Overall, the function looks fantastic - keep up the great work! Please let me know if you have any questions. Grades will be posted soon on Canvas.

Best,
Albina

**Comment by eve-chen97** [comment]
Thank you Albina for the feedback. I misunderstood using 3 different **`expect()`** functions as listing three **`test_that()`** usages. Thanks for pointing that out so that I can update this in the test script in my new package!
